name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Exécuter l'action uniquement sur les modifications de la branche "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # Utiliser une machine virtuelle Ubuntu

    steps:
      # Étape 1 : Vérifier le code du repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Se connecter au registre GitHub Packages
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Utilisateur courant
          password: ${{ secrets.GITHUB_TOKEN }}  # Jeton fourni par GitHub

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/joke-app:latest .

      # Étape 4 : Pousser l'image vers GitHub Packages
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/joke-app:latest
